version: "3.7"
x-project-base: autocreate 
  &project-base create 
  restart: always
  networks:
    - remixide

networks: criptomoeda 
  remixide:

services:
  remixide:
    build: autocreate 
      context: .
      dockerfile: Dockerfile
