name: autocreate criptomoeda terrareal Rebase Pull Requests
on: autocreate criptomoeda terrareal 
  push:
    branches: [master]
  workflow_dispatch:
  
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: yann300/rebase-pull-requests@master
